{
 "title": "Chapter 9.02",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Highest Magnitude",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "event",
     "query": "SELECT \"magnitude\" FROM \"event\" WHERE $timeFilter AND \"magnitude\" >= 2.0 GROUP BY \"tag_place\", \"tag_time\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Most Recent",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "5 Highest Magnitude",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "tag_place" ], "type": "tag" }
     ],
     "measurement": "event",
     "query": "SELECT \"magnitude\" FROM \"event\" WHERE (\"magnitude\" >= 2.0) AND $timeFilter GROUP BY \"tag_place\"",
     "select": [
      [
       { "params": [ "magnitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "magnitude >= 2.0", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "5 Most Recent",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "California",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "tag_latitude" ], "type": "tag" },
      { "params": [ "tag_longitude" ], "type": "tag" }
     ],
     "measurement": "event",
     "query": "SELECT \"magnitude\" FROM \"event\" WHERE $timeFilter AND (\"magnitude\" >= 2.0) GROUP BY \"tag_latitude\", \"tag_longitude\"",
     "select": [
      [
       { "params": [ "magnitude" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "North America",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 18 },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Oceania",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 18 },
   "targets": [
    { "panelId": 12 }
   ]
  }
 ]
}