{
 "title": "Chapter 9.01",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Station",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>\n  <center>San Francisco CA (KSFO)</center>\n</h1> "
   }
  },
  {
   "title": "Current Condtions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "textDescription",
     "query": "SELECT \"value\" FROM \"textDescription\" WHERE (\"station\" = 'KSFO') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$col $measurement",
     "query": "SELECT mean(\"value\") FROM \"heatIndex\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col $measurement",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col $measurement",
     "query": "SELECT mean(\"value\") FROM \"windChill\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Moisture",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$col $measurement",
     "query": "SELECT mean(\"value\") FROM \"dewpoint\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col $measurement",
     "query": "SELECT mean(\"value\") FROM \"relativeHumidity\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col $measurement",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Barometer Reading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "$col $measurement ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "barometricPressure",
     "query": "SELECT mean(\"value\")  / 1000 FROM \"barometricPressure\" WHERE (\"station\" = 'KSFO') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "title": "Barometer Reading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "suffix: kPa/hr" } },
   "targets": [
    {
     "alias": "$col $measurement ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "barometricPressure",
     "query": "SELECT derivative(mean(\"value\"), 1h)  / 1000 FROM \"barometricPressure\" WHERE (\"station\" = 'KSFO') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "derivative" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "alias": "$col $measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "windSpeed",
     "query": "SELECT mean(\"value\") FROM \"windSpeed\" WHERE (\"station\" = 'KSFO') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000 * 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    },
    {
     "alias": "$col $measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "windSpeed",
     "query": "SELECT distinct(\"value\") FROM \"windDirection\" WHERE (\"station\" = 'KSFO') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000 * 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Wind Gust",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "alias": "$col $measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "windGust",
     "query": "SELECT mean(\"value\") FROM \"windGust\" WHERE (\"station\" = 'KSFO') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000 * 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    },
    {
     "alias": "$col $measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "windSpeed",
     "query": "SELECT distinct(\"value\") FROM \"windDirection\" WHERE (\"station\" = 'KSFO') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000 * 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "title": "Visibility",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "alias": "$col $measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "visibility",
     "query": "SELECT mean(\"value\") /1000 FROM \"visibility\" WHERE (\"station\" = 'KSFO') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "title": "Base panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  }
 ]
}