services:
  grafana:
    image: "grafana/grafana:${GRAF_TAG-latest}"
    ports:
      - "3000:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=true
    volumes:
      - "${PWD-.}/grafana:/var/lib/grafana"
