{
 "title": "Chapter 7.03 Stat Visualization",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Basic stat",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"temperature\" WHERE (\"station\"::tag = 'KSFO') AND $timeFilter"
    }
   ]
  },
  {
   "title": "Stat with Area",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"temperature\" WHERE (\"station\" = 'KSFO') AND $timeFilter"
    }
   ]
  },
  {
   "title": "Stat with mapping",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "temperature",
     "query": "SELECT \"value\" FROM \"temperature\" WHERE (\"station\" = 'KSFO') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "title": "Stat with Area and Mapping",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "title": "Station temperatures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col $measurement $tag_station",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE $timeFilter GROUP BY time($__interval), \"station\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}