
pull:
	docker-compose pull

up:
	docker-compose up --pull -d

down:
	docker-compose down

start:
	docker-compose start

stop:
	docker-compose stop

restart:
	docker-compose restart

clean:
	docker-compose rm -vs

auto: pull up
