{
 "title": "Chapter 10.02 Template Variables",
 "time": { "from": "2023-02-06T08:00:00.000Z", "to": "2023-02-14T07:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "311Category",
    "label": "311 Category",
    "query": "{\"find\": \"terms\", \"field\": \"Category.keyword\"}"
   },
   {
    "name": "HistInterval",
    "label": "Histogram Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "FieldName",
    "label": "Field Name",
    "query": "{\"find\": \"fields\", \"type\": \"keyword\"}"
   },
   {
    "name": "FieldTerms",
    "label": "Field Terms",
    "query": "{\"find\": \"terms\", \"field\": \"$FieldName.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "$311Category by Supervisor District",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "SupervisorDistrict.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      {
       "field": "Opened",
       "id": "2",
       "settings": { "interval": "$HistInterval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "Category.keyword:$311Category",
     "timeField": "Opened"
    }
   ]
  },
  {
   "title": "Supervisor District",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "SupervisorDistrict.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      {
       "field": "Opened",
       "id": "2",
       "settings": { "interval": "$HistInterval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "Opened"
    }
   ]
  },
  {
   "title": "$311Category by Supervisor District",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:509",
       "fake": true,
       "field": "SupervisorDistrict.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:510",
       "field": "Opened",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:507", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "Category.keyword:$311Category",
     "timeField": "Opened"
    }
   ]
  },
  {
   "title": "$FieldName:$FieldTerms by Supervisor District",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "SupervisorDistrict.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      {
       "field": "Opened",
       "id": "2",
       "settings": { "interval": "$HistInterval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "$FieldName.keyword:$FieldTerms",
     "timeField": "Opened"
    }
   ]
  }
 ]
}