services:
  grafana:
    image: "grafana/grafana:${GRAF_TAG-latest}"
    ports:
      - "3000:3000"
    volumes:
      - "${PWD-.}/grafana:/var/lib/grafana"

  influxdb:
    image: "influxdb:${INFL_TAG-latest}"
    ports:
      - "8086:8086"
    volumes:
      - "${PWD-.}/influxdb2:/var/lib/influxdb2"

  python:
    build: .
    image: "python/ch9"
    environment:
      TZ: "America/Los_Angeles"
    volumes:
      - "${PWD-.}/app:/usr/src/app"
      - "${PWD-.}/data:/data"
